language: php
php:
    - 7.0
install:
    - composer install
script:
    - php vendor/bin/phpunit --bootstrap vendor/autoload.php -c ./phpunit.xml ./Tests
after_script:
    - php vendor/bin/coveralls -v